### ISSUE TITLE
Add support for mocking the "this" context

### ISSUE THREAD

**Issue by lombardo-staytuned** [jamauro/method#15]
When i trying to test a method i am facing issues mocking the this.userId, 

For example in mdg:validated-method package we have the  `_execute` function, that receive a context as the first parameter, 
Is it possible to implement something similar or is there other way for mocking the context

**Comment by jamauro** [comment]
Thanks for reporting. I plan to address this soon. I'm thinking of using `.call` so that it fits more into standard JS. 

```js
myMethod.call(context, ...args)
```

It will invoke the method directly without going through Meteor's `applyAsync` code path, the same as ValidatedMethod's `._execute`, which imo feels a little more obscure. 

Let me know if you have any thoughts here.

**Comment by lombardo-staytuned** [comment]
> Thanks for reporting. I plan to address this soon. I'm thinking of using `.call` so that it fits more into standard JS.
> 
> ```js
> myMethod.call(context, ...args)
> ```
> 
> It will invoke the method directly without going through Meteor's `applyAsync` code path, the same as ValidatedMethod's `._execute`, which imo feels a little more obscure.
> 
> Let me know if you have any thoughts here.

Yeap, make more sense using call,

**Comment by jamauro** [comment]
I just published `v1.8.0` that adds this feature. Thanks for requesting it!
